authors:
  ayodeji:
    name: Ayodeji Seriki
    description: Technical Writer
    avatar: https://github.com/ayodejimicheal337-netizen.png
    url: https://github.com/ayodejimicheal337-netizen
  team:
    name: The Blog Team
    description: Content Creators
    avatar: https://github.com/squidfunk.png 









